### ISSUE TITLE
Allow HTML escaping to be disabled

### ISSUE THREAD

**Issue by camstuart** [softmoth/raku-Template-Mustache#39]
Hi,

I am interpolating JSON into a mustache template and the quoted field names of the JSON object are being HTML escaped.

Data being passed to the template:

```json
[
  {
    "x": 1599160499999,
    "text": "entry: 53.13 stop: 52.86435",
    "title": "ENTRY"
  }
]
```
Template:
```
{
        type : 'flags',
        data : {{signals}},
        onSeries : 'candlestick',
        shape : 'flag'
},
```

Generated to my HTML/JavaScript on disk:
```json
data : [
  {
    &quot;x&quot;: 1599160499999,
    &quot;text&quot;: &quot;entry: 53.13 stop: 52.86435&quot;,
    &quot;title&quot;: &quot;ENTRY&quot;
  }
]
```

When I pass this data into the template, it would be great if I could "disable" escaping. EG mark this html contect as "safe"
Perhaps something like:  

```raku
my $html = $stache.render('highchart-candlestick', {
    signals => ( :content( to-json(@signal-series) ), :html-safe(True) )
});
```

Note: `to-json` being used from `JSON::Fast`

**Comment by softmoth** [comment]
Hi, Cam. I'm sorry I didn't see this earlier.

If you use three curly braces, no escaping is done, for example:  `{{{signals}}}`.
