### ISSUE TITLE
Can't install Template::Mustache

### ISSUE THREAD

**Issue by coke** [softmoth/raku-Template-Mustache#40]
user in #raku on IRC just opened this ticket:

https://github.com/Raku/rakudoc/issues/10

which appears to be a result of an issue with a Template::Mustache dependency.

**Comment by coke** [comment]
tagging that user: @Pim-tech

**Comment by softmoth** [comment]
Thank you. I posted a bit more information over on that ticket, but I think this was probably a transient issue? At least a current clean build of Rakudo & zef can `zef install Template::Mustache` OK. Thanks for your help in forwarding this problem.
